Add file io
perrymant/moneymaker pull request #10
Opened 2018-09-10 11:17 UTC by perrymant

1. This branch introduces the fileIO class, and can now read/write/append to/from file.
2. I had some git issues that I have hopefully sorted with this branch, including the readme.md

2018-09-10 12:38 UTC, kinbiko requested changes
I see that you're adding file IO, and it looks like it works. But I don't see any requirements that say that we should do this? Can we update the README with this?

Let's go over what happened with the `master` branch when we meet up next.

Thanks for joining the slack btw!

2018-09-10 12:38 UTC, kinbiko commented on README.md
> +<pre>
`<pre>` is identical to triple backticks in markdown

2018-09-10 12:38 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/FileIO.java
> +    static String read(String fileName) throws IOException {
No need for this to be `static`. In fact, other than `main`, try and avoid `static` unless you have a strong reason to use it.

2018-09-10 12:38 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/FileIO.java
> +    static String read(String fileName) throws IOException {
If you've got `throws BlahException` in a method declaration that's a sign that you're doing something wrong. Remember: avoid checked exception - always wrap in (preferably your own implementation of a) RuntimeException.

2018-09-10 12:38 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/FileIO.java
> +        while ((s = text.readLine()) != null) {
There is [a lot easier way](https://stackoverflow.com/a/326440/2422278) of reading files than this. E.g.

```java
return new String(Files.readAllBytes(Paths.get(fileName)), Charset.defaultCharset());
```

2018-09-10 12:38 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/FileIO.java
> +        writer.close();
Have a look at what try-with-resources or `finally` does in Java. Essentially we need to guarantee that `writer.close()` gets called, and if `writer.write(data)` throws an exception we end up not closing it.

2018-09-10 12:38 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/FileIO.java
> +        BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true));
magic boolean: What is `true`? Create a variable (or even a constant) so you can give it a name.

2018-09-10 12:38 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/Logger.java
> +        System.out.println(logo);
Do we always want to print the logo whenever we want to log something in our application? I'm guessing no - maybe we should only print the logo once on startup?

2018-09-10 12:38 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/FileIOTest.java
> +        String fileName = "src/test/java/io/github/perrymant/moneymaker/file_with_data";
sounds like this file should be in `src/test/resources` instead. Applies throughout

2018-09-10 12:38 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/FileIOTest.java
> +        assertEquals(FileIO.read(fileName), dataToWrite);
Doesn't this kinda remove the need for the `canReadData` test?

2018-09-10 12:38 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/FileIOTest.java
> +        new FileIO().append(dataToAppend, fileName);
Doesn't this test remove the need for the `canWriteData()` test?

2018-09-10 12:38 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/file_with_data
> +2018/01/01, CREDIT, 200, 200, Got paid
Should these files even be committed to Git if we only want to make sure we can read and write files? I suggest putting them in a `src/test/resources/dump/` folder, and then adding this folder to your `.gitignore`

2018-09-11 19:49 UTC, closed without merging

2018-09-11 20:29 UTC, kinbiko commented
Why was this one closed?

2018-09-11 20:47 UTC, perrymant commented
... sorry, didn't know the procedure!
I thought I would re-state the situation in a new PR.