currency now outputs in format £1,234,567.89
perrymant/moneymaker pull request #19
Opened 2018-09-30 10:22 UTC by perrymant

- This branch now outputs in format £1,234,567.89
HOWEVER
- It doesn't say GBP at the end... is that a big deal? I can change if desirable!
i.e.:
£1,234,567.89 GBP

2018-09-30 11:19 UTC, kinbiko requested changes
Looks like it does what it says on the can! 🎉 Now let's just refactor and simplify a bit.

Let's simplify a lot of the logic here. I think I've spotted the stackoverflow question you copied from, but I think that solution is far more complex than it needs to be for this task.

To answer your question in the description: I don't think it needs to say `GBP` at the end.

2018-09-30 11:19 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/ReportLine.java
> +    private Locale getLocalFromISO(String ISO_4217_GBP){
There are a few improvements we can make here. Let me go over my thought process:

1st iteration: Just remove `FromISO` as this should be obvious from the input parameter. This applies to all methods you want to name in the `BarFromFoo` format. Also `s/Local/Locale`.
2nd iteration: we don't ever use anything other than this `ISO_4217_GBP` value, so let's just make it a `private static final` constant in this class, and get rid of the parameter.
3rd iteration: Notice that a money format constant doesn't intuitively belong in a `ReportLine` class and extract this logic to another class.

Foreshadowing: this will make testing a lot nicer.

2018-09-30 11:19 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/ReportLineTest.java
> +    public void canDisplayCurrenciesInISOFormat() {
As it currently stands this test is just copying the logic of the implementation. There should be *no business logic in tests*. In particular, loops (in any form) should only appear in very special circumstances, and `if` statements should never occur.

I think perhaps we'll be better off having a `MoneyFormatter` class that has a `public String formatPounds(long pence)` method. This can then easily be tested. Inputs and outputs are intuitive, rather than having to faff about with Locales and NumberFormat. E.g.

```
input: 100, output: "£1.00"
input 54, output: "£0.54"
```

2018-09-30 11:19 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/ReportLineTest.java
> +                        currencyInstance.format((double)AMOUNT/100),
This should just be the string you expect instead of re-doing the calculation here.

2018-09-30 11:19 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/ReportLine.java
> +            String code = NumberFormat.getCurrencyInstance(locale).
Do we need all this? Can we not reduce this method into `return NumberFormat.getCurrencyInstance(Locale.UK);` instead? In this case, do we even need a separate method to get this Locale? I wouldn't be surprised if our solution to this ends up being a new class with one method of just a few lines of code.

2018-09-30 11:19 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/ReportLineTest.java
> +    public void canDisplayCurrenciesInISOFormat() {
I disagree with this rename. It's testing a lot more than just the currencies.

2018-10-01 21:30 UTC, perrymant commented
- Logic simplified.
- Removed unnecessary code brought in from SO.
- created MoneyFormatter class to deal with currency formatting.

2018-10-01 22:13 UTC, kinbiko approved these changes
You're pretty much there with this implementation, so I'm approving.

There are a few improvements that we ought to make first though. I'm trusting you'll make those without needing me to look over it afterwards.

2018-10-01 22:13 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/MoneyFormatter.java
> +    private static final Locale UK = Locale.UK;
This can be statically imported instead.

2018-10-01 22:13 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/MoneyFormatter.java
> +        NumberFormat currencyInstance = NumberFormat.getCurrencyInstance(UK);
This variable can be a `private static final` field - no need to re-create it every time `formatPounds` is called.

2018-10-01 22:13 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/MoneyFormatter.java
> +        return currencyInstance.format(value);
Can inline this value. Having `value` as a variable name is a bit of a code smell. Can almost always (exception: key-value pairs in maps) use a better variable name, or avoid this variable entirely.

2018-10-01 22:13 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/MoneyFormatterTest.java
> +    public void canIntToCurrencyFormat() {
What about:
- [ ] 0
- [ ] negative values
- [ ] decimals smaller than 1 pound

Add separate test cases for these.

2018-10-01 22:13 UTC, kinbiko commented on src/main/java/io/github/perrymant/moneymaker/MoneyFormatter.java
> +    static String formatPounds(int amount) {
There's no need for this to be `static`. Avoid static whenever possible as it makes is hard to mock out in tests, should we ever need to.

2018-10-02 06:13 UTC, merged