reportController test passes
perrymant/moneymaker pull request #49
Opened 2019-01-28 15:04 UTC by perrymant

2019-01-29 22:25 UTC, kinbiko requested changes

2019-01-29 22:25 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +                    .andExpect(content().string(equalTo(targetJSON)));
How exact does this string have to be? I'm guessing that if you add a space to either payload it will fail. Please let me know if that's not the case. This is a bit too rigid. Could we assert that `report[0].amount` is 125 etc instead? That will be more useful going forward as well.

2019-01-29 22:25 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +        } catch (Exception e) {
For tests it's OK to `throws Exception` always, even if it doesn't throw anything. Ideally the code you invoke doesn't throw checked exceptions, however sometimes (like this time) you have to use third-party libraries that don't agree with that philosophy.

2019-01-29 22:25 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +            e.printStackTrace();
For every `e.printStackTrace();` you leave in your code trump gains a follower. Do the right thing. `throw new RuntimeException(e);`.

If we've not yet discussed why this is evil, have a think and let me know what your thoughts are.

2019-01-29 22:25 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +    private
That's an interesting formatting. Let's keep `private` on the same line as the type and the variable name.

2019-01-30 17:49 UTC, perrymant commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +            e.printStackTrace();
I think we probably have discussed this! I went over my notes and couldn't find anything to stop me from writing this. Have amended notes!

2019-01-30 18:33 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +                    .andExpect(content().string(equalTo(targetJSON)));
*sigh*. Yup. That one is on me. Although, we now correctly check *one* property, let's practice a bit more and get really familiar with the syntax. Let's assert the entire payload, or as much as is reasonable.

2019-02-04 19:45 UTC, perrymant commented
Now testing all key/values in the json file.

2019-02-04 19:50 UTC, kinbiko approved these changes
Looks pretty good to me. Nothing major so feel free to address without assigning the review to me again.

2019-02-04 19:50 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +    public void assertJSONResponse_usingContains() throws Exception {
This test doesn't really add any value compared to the other one, let's delete it.

2019-02-04 19:50 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +    private static final String BASE_URL = "/report";
Move this above the non-static field.

2019-02-04 19:50 UTC, kinbiko commented on src/test/java/io/github/perrymant/moneymaker/HitRestEndpointTest.java
> +public class HitRestEndpointTest {
Let's give this class a better name. `GetReportTest` for example.

2019-02-06 09:58 UTC, merged